# Generated by Django 2.0 on 2020-04-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200410_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='national_id',
            new_name='confirm',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type_of_user',
            new_name='reg_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nearest_town',
        ),
    ]
